import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

/**
 * Deployment Script — ZK Resume Protocol
 * ─────────────────────────────────────────────────────────
 * Order:
 *   1. Deploy ResumeVerifier (Groth16 auto-generated contract)
 *   2. Deploy ResumeRegistry (main logic, constructor takes verifier addr)
 *   3. Register universities
 *   4. Save addresses to deployments/<network>.json
 *
 * Run:
 *   npx hardhat run scripts/deploy.ts --network sepolia
 */
async function main() {
  const [deployer] = await ethers.getSigners();
  const network = await ethers.provider.getNetwork();
  const networkName = network.name === "unknown" ? "localhost" : network.name;

  console.log("════════════════════════════════════════════");
  console.log("  ZK Resume Protocol — Deployment");
  console.log("════════════════════════════════════════════");
  console.log(`  Network   : ${networkName} (chainId: ${network.chainId})`);
  console.log(`  Deployer  : ${deployer.address}`);
  console.log(
    `  Balance   : ${ethers.formatEther(
      await ethers.provider.getBalance(deployer.address)
    )} ETH`
  );
  console.log("────────────────────────────────────────────");

  // ── Step 1: Deploy Groth16 Verifier ────────────────────────────
  // ResumeVerifier.sol is AUTO-GENERATED by snarkjs.
  // It must exist in contracts/ before running this script.
  // Run: snarkjs zkey export solidityverifier resume_final.zkey contracts/ResumeVerifier.sol
  console.log("\n[1/3] Deploying ResumeVerifier (Groth16)...");
  const ResumeVerifier = await ethers.getContractFactory("Groth16Verifier");
  const resumeVerifier = await ResumeVerifier.deploy();
  await resumeVerifier.waitForDeployment();
  const verifierAddress = await resumeVerifier.getAddress();
  console.log(`  ✓ ResumeVerifier deployed: ${verifierAddress}`);

  // ── Step 2: Deploy ResumeRegistry ──────────────────────────────
  console.log("\n[2/3] Deploying ResumeRegistry...");
  const ResumeRegistry = await ethers.getContractFactory("ResumeRegistry");
  const resumeRegistry = await ResumeRegistry.deploy(verifierAddress);
  await resumeRegistry.waitForDeployment();
  const registryAddress = await resumeRegistry.getAddress();
  console.log(`  ✓ ResumeRegistry deployed: ${registryAddress}`);

  // ── Step 3: Register Initial Universities ──────────────────────
  // In production, this would be done via governance.
  // For demo/testnet, we register the deployer as a test university.
  console.log("\n[3/3] Registering test university...");
  const tx = await resumeRegistry.registerUniversity(
    deployer.address,
    "ZK University (Testnet Demo)"
  );
  await tx.wait();
  console.log(`  ✓ University registered: ${deployer.address}`);

  // ── Save Deployment Addresses ───────────────────────────────────
  const deploymentData = {
    network: networkName,
    chainId: network.chainId.toString(),
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
    contracts: {
      ResumeVerifier: {
        address: verifierAddress,
        note: "Auto-generated Groth16 verifier — do not edit",
      },
      ResumeRegistry: {
        address: registryAddress,
        note: "Main credential registry with ZK + EAS validation",
      },
    },
    eas: {
      network: networkName,
      easContractAddress: "0xC2679fBD37d54388Ce493F1DB75320D236e1815e",
      schemaUID: process.env.SCHEMA_UID || "PENDING — register schema first",
    },
  };

  const deploymentsDir = path.join(__dirname, "..", "deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }

  const deploymentPath = path.join(deploymentsDir, `${networkName}.json`);
  fs.writeFileSync(deploymentPath, JSON.stringify(deploymentData, null, 2));

  console.log("\n════════════════════════════════════════════");
  console.log("  Deployment Complete");
  console.log("════════════════════════════════════════════");
  console.log(`  ResumeVerifier : ${verifierAddress}`);
  console.log(`  ResumeRegistry : ${registryAddress}`);
  console.log(`  Saved to       : deployments/${networkName}.json`);

  if (networkName === "sepolia") {
    console.log("\n  Verify on Etherscan:");
    console.log(
      `  npx hardhat verify --network sepolia ${verifierAddress}`
    );
    console.log(
      `  npx hardhat verify --network sepolia ${registryAddress} "${verifierAddress}"`
    );
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
