// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IResumeVerifier
 * @notice Interface for the auto-generated Groth16 Solidity verifier.
 *         This file is generated by snarkjs — do NOT implement manually.
 *
 * The verifier checks the Groth16 proof cryptographically on-chain.
 * Public signals layout (3 signals, matching circuit output):
 *   _pubSignals[0] = qualified     (1 = proven qualified; enforced by circuit constraint)
 *   _pubSignals[1] = threshold     (minimum CGPA x 100, e.g. 800)
 *   _pubSignals[2] = studentIdHash (Poseidon hash of studentId)
 */
interface IResumeVerifier {
    /**
     * @notice Verifies a Groth16 ZK proof.
     * @param _pA  Proof point A (G1)
     * @param _pB  Proof point B (G2)
     * @param _pC  Proof point C (G1)
     * @param _pubSignals  Public signals: [qualified, threshold, studentIdHash]
     * @return bool  True if proof is valid, false otherwise
     */
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[3] calldata _pubSignals
    ) external view returns (bool);
}
