// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./IResumeVerifier.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ResumeRegistry
 * @author ZK Resume Protocol
 * @notice Pure on-chain credential verification via ZK-SNARKs + EAS.
 *
 * ╔══════════════════════════════════════════════════════════════════╗
 * ║  ARCHITECTURE (Fully Decentralized)                             ║
 * ║                                                                  ║
 * ║  1. University creates EAS attestation (off-chain signed)       ║
 * ║  2. Student generates Groth16 ZK proof locally (in browser)     ║
 * ║  3. Student calls verifyCredential() with proof + EAS sig       ║
 * ║  4. Contract:                                                    ║
 * ║     a) Recovers EAS signer via ecrecover                        ║
 * ║     b) Validates signer is a registered university              ║
 * ║     c) Calls Groth16 verifier contract                          ║
 * ║     d) Emits CredentialVerified event                           ║
 * ║  5. Employer reads on-chain mapping — no trusted intermediary   ║
 * ╚══════════════════════════════════════════════════════════════════╝
 *
 * @dev No backend. No API. No centralized oracle. 100% on-chain.
 */
contract ResumeRegistry is ReentrancyGuard, Ownable {

    // ─────────────────────────────────────────────────────────────────
    // State Variables
    // ─────────────────────────────────────────────────────────────────

    /// @notice The Groth16 verifier contract (auto-generated by snarkjs)
    IResumeVerifier public immutable verifier;

    /// @notice EAS contract address on Sepolia
    address public constant EAS_SEPOLIA = 0xC2679fBD37d54388Ce493F1DB75320D236e1815e;

    /// @notice Registered university signers (address => name)
    mapping(address => string) public registeredUniversities;

    /// @notice Verification results per holder
    /// holder => VerificationRecord
    mapping(address => VerificationRecord) public verifications;

    /// @notice All verified holders list for explorer
    address[] public verifiedHoldersList;

    /// @notice EAS attestation UIDs already consumed (replay protection)
    mapping(bytes32 => bool) public usedAttestations;

    /// @notice Employer recorded ATS verdicts (employer => candidate => verdict)
    mapping(address => mapping(address => ATSVerdict)) public employerVerdicts;

    // ─────────────────────────────────────────────────────────────────
    // Structs
    // ─────────────────────────────────────────────────────────────────

    struct VerificationRecord {
        bool isVerified;
        uint256 threshold;          // Minimum CGPA × 100 used in proof
        uint256 verifiedAt;         // Block timestamp
        bytes32 attestationUID;     // EAS attestation UID
        address universityAddress;  // Which university issued
        uint256 blockNumber;
    }

    struct ATSVerdict {
        bool qualified;
        uint256 score;
        uint256 timestamp;
        string ipfsCID;
    }

    // ─────────────────────────────────────────────────────────────────
    // Events
    // ─────────────────────────────────────────────────────────────────

    /// @notice Emitted when a credential is successfully verified
    event CredentialVerified(
        address indexed holder,
        address indexed university,
        uint256 threshold,
        bytes32 attestationUID,
        uint256 blockNumber
    );

    /// @notice Emitted when a university is registered by owner
    event UniversityRegistered(address indexed universityAddress, string name);

    /// @notice Emitted when verification fails (for analytics)
    event VerificationFailed(address indexed holder, string reason);

    /// @notice Emitted when an employer records an ATS verdict
    event ATSVerdictRecorded(address indexed employer, address indexed candidate, bool qualified, uint256 score, string ipfsCID);

    // ─────────────────────────────────────────────────────────────────
    // Errors
    // ─────────────────────────────────────────────────────────────────

    error InvalidProof();
    error AttestationAlreadyUsed();
    error UniversityNotRegistered(address signer);
    error InvalidSignature();
    error ZeroAddress();

    // ─────────────────────────────────────────────────────────────────
    // Constructor
    // ─────────────────────────────────────────────────────────────────

    /**
     * @param _verifier Address of the deployed Groth16 verifier contract
     */
    constructor(address _verifier) Ownable(msg.sender) {
        if (_verifier == address(0)) revert ZeroAddress();
        verifier = IResumeVerifier(_verifier);
    }

    // ─────────────────────────────────────────────────────────────────
    // Core: Verify Credential
    // ─────────────────────────────────────────────────────────────────

    /**
     * @notice Verifies a ZK credential proof on-chain.
     *
     * @dev Verification steps:
     *   1. Check attestation not already used (replay protection)
     *   2. Recover university signer from EAS signature
     *   3. Confirm signer is a registered university
     *   4. Call Groth16 verifier with proof + public signals
     *   5. Store result and emit event
     *
     * @param _pA            Groth16 proof point A
     * @param _pB            Groth16 proof point B
     * @param _pC            Groth16 proof point C
     * @param _pubSignals    [qualified, threshold, studentIdHash] — public circuit signals
     * @param _attestationUID  EAS attestation UID (bytes32)
     * @param _easSignature    EAS signature from university (65 bytes)
     *
     * @return bool  True if credential verified successfully
     */
    function verifyCredential(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[3] calldata _pubSignals,
        bytes32 _attestationUID,
        bytes calldata _easSignature
    ) external nonReentrant returns (bool) {

        // ── Step 1: Replay Protection ──────────────────────────────
        if (usedAttestations[_attestationUID]) {
            revert AttestationAlreadyUsed();
        }

        // ── Step 2: Recover University Signer ─────────────────────
        // The university signs a hash of (attestationUID, threshold, studentIdHash)
        bytes32 messageHash = keccak256(
            abi.encodePacked(
                _attestationUID,
                _pubSignals[1],   // threshold  (index 1; [0]=qualified)
                _pubSignals[2]    // studentIdHash
            )
        );

        bytes32 ethSignedHash = keccak256(
            abi.encodePacked("\x19Ethereum Signed Message:\n32", messageHash)
        );

        address signer = _recoverSigner(ethSignedHash, _easSignature);
        if (signer == address(0)) revert InvalidSignature();

        // ── Step 3: Verify University is Registered ───────────────
        if (bytes(registeredUniversities[signer]).length == 0) {
            emit VerificationFailed(msg.sender, "University not registered");
            revert UniversityNotRegistered(signer);
        }

        // ── Step 4: Verify ZK Proof ───────────────────────────────
        // This calls the Groth16 verifier contract on-chain.
        // The proof cryptographically proves cgpa >= threshold
        // WITHOUT revealing cgpa.
        bool proofValid = verifier.verifyProof(_pA, _pB, _pC, _pubSignals);
        if (!proofValid) {
            emit VerificationFailed(msg.sender, "Invalid ZK proof");
            revert InvalidProof();
        }

        // ── Step 5: Mark attestation used + Store Result ──────────
        usedAttestations[_attestationUID] = true;

        bool isFirstVerification = !verifications[msg.sender].isVerified;

        verifications[msg.sender] = VerificationRecord({
            isVerified:       true,
            threshold:        _pubSignals[1],  // [0]=qualified, [1]=threshold
            verifiedAt:       block.timestamp,
            attestationUID:   _attestationUID,
            universityAddress: signer,
            blockNumber:      block.number
        });

        // Track unique holders
        if (isFirstVerification) {
            verifiedHoldersList.push(msg.sender);
        }

        emit CredentialVerified(
            msg.sender,
            signer,
            _pubSignals[0],
            _attestationUID,
            block.number
        );

        return true;
    }

    // ─────────────────────────────────────────────────────────────────
    // Read Functions
    // ─────────────────────────────────────────────────────────────────

    /**
     * @notice Check if a holder meets a given CGPA threshold.
     * @dev Used by employers — pure on-chain lookup, no API needed.
     * @param holder     Wallet address of the candidate
     * @param minThreshold  Minimum CGPA × 100 (e.g. 800 = 8.00)
     * @return qualified  True if holder's verified threshold >= minThreshold
     * @return record     Full verification record
     */
    function checkQualification(
        address holder,
        uint256 minThreshold
    ) external view returns (bool qualified, VerificationRecord memory record) {
        record = verifications[holder];
        qualified = record.isVerified && record.threshold >= minThreshold;
    }

    /**
     * @notice Get all verified holders (for the explorer dashboard).
     */
    function getAllVerifiedHolders() external view returns (address[] memory) {
        return verifiedHoldersList;
    }

    /**
     * @notice Total number of verified credentials.
     */
    function totalVerifications() external view returns (uint256) {
        return verifiedHoldersList.length;
    }

    // ─────────────────────────────────────────────────────────────────
    // Admin: Register Universities
    // ─────────────────────────────────────────────────────────────────

    /**
     * @notice Record ATS verdict for a candidate.
     */
    function recordATSVerdict(address candidate, bool qualified, uint256 score, string calldata ipfsCID) external {
        if (candidate == address(0)) revert ZeroAddress();
        employerVerdicts[msg.sender][candidate] = ATSVerdict({
            qualified: qualified,
            score: score,
            timestamp: block.timestamp,
            ipfsCID: ipfsCID
        });
        emit ATSVerdictRecorded(msg.sender, candidate, qualified, score, ipfsCID);
    }

    /**
     * @notice Register a university as a valid EAS signer.
     * @dev In a fully permissionless version, this could be governed
     *      by a DAO vote. For now, owner = protocol deployer.
     */
    function registerUniversity(
        address universityAddress,
        string calldata name
    ) external onlyOwner {
        if (universityAddress == address(0)) revert ZeroAddress();
        registeredUniversities[universityAddress] = name;
        emit UniversityRegistered(universityAddress, name);
    }

    // ─────────────────────────────────────────────────────────────────
    // Internal: ECDSA Recovery
    // ─────────────────────────────────────────────────────────────────

    function _recoverSigner(
        bytes32 hash,
        bytes calldata signature
    ) internal pure returns (address) {
        if (signature.length != 65) return address(0);

        bytes32 r;
        bytes32 s;
        uint8 v;

        assembly {
            r := calldataload(signature.offset)
            s := calldataload(add(signature.offset, 32))
            v := byte(0, calldataload(add(signature.offset, 64)))
        }

        if (v < 27) v += 27;
        if (v != 27 && v != 28) return address(0);

        return ecrecover(hash, v, r, s);
    }
}
